name: Publish Image to Dockerhub
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: dockerhub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: achyutakn/geg-app
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: npx build tailwindcss
      run: npx tailwindcss build -i css/main.css -o static/css/tailwind.css -c tailwind.config.js  --minify
    - name: build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
          
          
      
    
  
